Reddit_clone/config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs

  resources :posts, except: [:index]

  resources :subs, except: [:create, :destroy]
end

Reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord

  validates :title, presence: true

  belongs_to :user,
    foreign_key: :author_id,
    class_name: :User

  # belongs_to :sub,
  # foreign_key: :sub_id,
  # class_name: :Sub

  has_many :post_subs, inverse_of: :post

  has_many :subs, through: :post_subs, source: :sub


end

Reddit_clone/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :bigint(8)        not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord
  validates :sub_id, uniqueness: { scope: :post_id }
  
  belongs_to :post
  belongs_to :sub

end

Reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, :moderator_id, presence: true

  belongs_to :user,
    foreign_key: :moderator_id,
    class_name: :User

  # has_many :posts,
  # foreign_key: :sub_id,
  # class_name: :Post

  has_many :post_subs, inverse_of: :sub

  has_many :posts,
  through: :post_subs,
  source: :post
end

Reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  
  has_many :subs,
    foreign_key: :moderator_id,
    class_name: :Subs
    
  has_many :posts,
  foreign_key: :author_id,
  class_name: :Post
  
  attr_reader :password
  
  before_validation :ensure_session_token
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)    
  end
  
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
  
  def reset_session_token
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
end

Reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  helper_method :current_user, :logged_in?

  def login(user)
    session[:session_token] = user.reset_session_token
    @current_user = user
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def current_user
    @current_user = User.find_by(session_token: session[:session_token])
  end
end

Reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_login
  def new
    @post = Post.new

    render :new
  end

  def create
    @post = Post.new(post_params)
    # @post.sub_id = params[:sub_id]
    @post.author_id = current_user.id

    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to sub_url(@post.sub_id)
    end
  end


  def edit
    @post = current_user.posts.find(params[:id])

    render :edit
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])

    render :show
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub_url)
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

end

Reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(params[:user][:username],params[:user][:password])
    if user
      login(user)
      redirect_to subs_url
    else
      flash[:errors] = ['Not good']
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

Reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login
  
  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def new
    @sub = Sub.new
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = current_user.subs.find(params[:id])
    
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      redirect_to sub_url(@sub)
    end 
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id 
    if @sub.save
      redirect_to sub_url(@sub)
    else 
      flash[:errors] = @sub.errors.full_messages
      render :new 
    end 
      
  end
  
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

Reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

Reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

Reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

Reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

Reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

Reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

Reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
    <% if flash[:errors] %>
      <% flash[:errors].each do |err| %>
      <li><%= err %></li>
      <% end %>
    <% end %>
  </ul>
    <% if logged_in? %>
      <%= button_to 'Sign Out', session_url, method: :delete %>
    <% end %>

    <%= yield %>
  </body>
</html>

Reddit_clone/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

<form class="" action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <label>
    Subs
    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
      <input <%= 'checked' if @post.subs.include?(sub) %> type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"> <%= sub.title %><br>
    <% end %>
  </label>
  <label>
    Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
  <label>
    URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
  <label>
    Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>

  <input type="submit" name="" value="Create Post">
</form>

Reddit_clone/app/views/posts/new.html.erb
<h1>Add a New Post</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<form class="" action="<%= posts_url %>" method="post">

  <label>
    Subs
    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"> <%= sub.title %><br>
    <% end %>
  </label>
  <label>
    Title
    <input type="text" name="post[title]" value="">
  </label>
  <label>
    URL
    <input type="text" name="post[url]" value="">
  </label>
  <label>
    Content
    <input type="text" name="post[content]" value="">
  </label>

  <input type="submit" name="" value="Create Post">
</form>

Reddit_clone/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<ul>
  <li><%= @post.url %></li>
  <li><%= @post.content %></li>
</ul>

<a href="<%= subs_url %>">All subs</a>

Reddit_clone/app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

Reddit_clone/app/views/subs/index.html.erb
<h1>All Subs!!!!!!!!</h1>

<a href="<%= new_sub_url %>">Create a New Sub like a boss</a>

<ul>
<% @subs.each do |sub| %>

  <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>

<% end %>
</ul>

Reddit_clone/app/views/subs/new.html.erb
<marquee><h1>Create New Sub</h1></marquee>

<form class="" action="<%= subs_url %>" method="post">

  <label>
    Title
    <input type="text" name="sub[title]" value="">
  </label>
  <label>
    Description
    <input type="text" name="sub[description]" value="">
  </label>

  <input type="submit" name="" value="Create New Sub">

</form>

Reddit_clone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<a href="<%= subs_url %>">All the SuBs</a>

<ul>
  <li><%= @sub.user.username %></li>
  <li><%= @sub.description %></li>
</ul>

<h2>Posts</h2>

<% @sub.posts.each do |post| %>
  <ul>
    <a href="<%= post_url(post) %>"><%= post.title %></a>
  </ul>
<% end %>

<a href="<%= new_post_url %>">Create a New Post</a>

Reddit_clone/app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<form action="<%= users_url %>" method="post">

  <label>
    Username
    <input type="text" name="user[username]" value="">
  </label>
  <label>
    Password
    <input type="text" name="user[password]" value="">
  </label>
  <input type="submit" name="" value="Sign up">
</form>